# ------------------------------ language plugins ------------------------------
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'
hook_add = '''
  " enable sorting groups
  let g:scala_sort_across_groups = 1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = [
  'elm',
  'eruby',
  'haskell',
  'hs',
  'javascript',
  'javascriptreact',
  'json',
  'lhs',
  'markdown',
  'purescript',
  'python',
  'rust',
  'sbt',
  'scala',
  'typescript',
  'typescriptreact',
  'vim',
  'yaml'
]
merged = 0
rev = 'release'
hook_add = '''
  set updatetime=300
  set shortmess+=c
  set signcolumn=yes

  autocmd CursorHold *.scala silent call CocActionAsync('highlight')

  " scrollable in popup menu
  if has('nvim')
    nnoremap <silent><expr> <C-j> coc#float#has_float() ? coc#float#scroll(1) : "\<C-j>"
    nnoremap <silent><expr> <C-k> coc#float#has_float() ? coc#float#scroll(0) : "\<C-k>"
  else
    nnoremap <silent><expr> <C-j> <SID>scroll_cursor_popup(1) ? "\<Esc>" : "\<C-d>"
    nnoremap <silent><expr> <C-k> <SID>scroll_cursor_popup(0) ? "\<Esc>" : "\<C-u>"

    function! s:find_cursor_popup(...) abort
      let radius = get(a:000, 0, 2)
      let srow   = screenrow()
      let scol   = screencol()

      " it's necessary to test entire rect, as some popup might be quite small
      for r in range(srow - radius, srow + radius)
        for c in range(scol - radius, scol + radius)
          let winid = popup_locate(r, c)
          if winid != 0
            return winid
          endif
        endfor
      endfor

      return 0
    endfunction

    function! s:scroll_cursor_popup(down) abort
      let winid = s:find_cursor_popup()
      if winid == 0
        return 0
      endif

      let pp = popup_getpos(winid)
      call popup_setoptions( winid,
            \ {'firstline' : pp.firstline + ( a:down ? 1 : -1 ) } )

      return 1
    endfunction
  endif

  nmap     <silent>       [e         <Plug>(coc-diagnostic-prev)
  nmap     <silent>       ]e         <Plug>(coc-diagnostic-next)
  nmap     <silent>       <Space>q   :<C-u>CocFix<CR>
  vmap     <silent>       <Space>q   <Plug>(coc-codeaction-selected)
  nmap     <silent>       gd         <Plug>(coc-definition)
  nmap     <silent>       gy         <Plug>(coc-type-definition)
  nmap     <silent>       gi         <Plug>(coc-implementation)
  nmap     <silent>       gr         <Plug>(coc-references)
  nmap     <silent>       <leader>rn <Plug>(coc-rename)
  nnoremap <silent>       K          :call CocAction('doHover')<CR>
  nnoremap <silent>       <Space>c   :CocCommand<CR>
  nnoremap <silent>       <Space>f   :call CocAction('format')<CR>
  nnoremap <silent>       <Space>i   :CocCommand editor.action.organizeImport<CR>
  nnoremap <silent>       <Space>a   :<C-u>CocList diagnostics<CR>
  nnoremap <silent>       <Space>o   :<C-u>CocList outline<CR>
  nnoremap <silent>       <Space>s   :<C-u>CocList -I symbols<CR>
  nnoremap <silent>       <Space>j   :<C-u>CocNext<CR>
  nnoremap <silent>       <Space>k   :<C-u>CocPrev<CR>
  nnoremap <silent>       <Space>p   :<C-u>CocListResume<CR>
  inoremap <silent><expr> <CR>       pumvisible() ? coc#_select_confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
'''

[[plugins]]
repo = 'voldikss/vim-skylight'
if = '''has('nvim')''' # only nvim >= 0.4.3
on_ft = [
  'elm',
  'eruby',
  'haskell',
  'hs',
  'javascript',
  'javascriptreact',
  'json',
  'lhs',
  'markdown',
  'purescript',
  'python',
  'rust',
  'sbt',
  'scala',
  'typescript',
  'typescriptreact',
  'vim',
  'yaml'
]
hook_add = '''
  let g:skylight_opener = 'CocAutoSplit'

  " preview by tag (support only coc.nvim)
  nnoremap <silent> gp :<C-u>Skylight!<CR>
  vnoremap <silent> gp :<C-u>Skylight!<CR>
  " Scroll Down
  nmap     <silent><expr> <C-f> skylight#float#has_scroll() ? skylight#float#scroll(1) : '<Plug>(SmoothieForwards)'
  " Scroll Up
  nmap     <silent><expr> <C-b> skylight#float#has_scroll() ? skylight#float#scroll(0) : '<Plug>(SmoothieBackwards)'
'''

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = 'elm'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
  'html',
  'javascript',
  'typescript',
]
hook_add = '''
  let g:user_emmet_leader_key = '<C-y>'
'''

# ------------------------------ document utility ------------------------------

# Markdown

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_no_default_key_mappings = 1
  let g:vim_markdown_folding_disabled        = 1
  let g:vim_markdown_conceal                 = 0
  let g:vim_markdown_conceal_code_blocks     = 0
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'
hook_add = '''
  nnoremap <silent><Space>@ :TableFormat<CR>
'''


[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = 'markdown'
hook_add = '''
  let g:preview_markdown_vertical    = 1
  let g:preview_markdown_auto_update = 1
'''

# reStructured code

[[plugins]]
repo = 'gu-fan/riv.vim'
on_ft = 'rst'
hook_add = '''
  let g:riv_disable_folding = 1
'''
