echo execute('CocInstall coc-eslint')
echo execute('CocInstall coc-yaml')
echo execute('CocInstall coc-tsserver')
echo execute('CocInstall coc-rls')
echo execute('CocInstall coc-metals')
echo execute('CocInstall coc-json')
