# ---------------------------------- General -----------------------------------

live_config_reload = true

# ------------------------------------ Font ------------------------------------

[font]

size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Thin"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

# ----------------------------------- window -----------------------------------

[window]
decorations = "None"
dynamic_title = true
# opacity = 0.9
opacity = 1.0

# ----------------------------------- Colors -----------------------------------

# tokyonight

# [colors.primary]
# background = '#1a1b26'
# foreground = '#a9b1d6'
#
# # Normal colors
# [colors.normal]
# black   = '#32344a'
# red     = '#f7768e'
# green   = '#9ece6a'
# yellow  = '#e0af68'
# blue    = '#7aa2f7'
# magenta = '#ad8ee6'
# cyan    = '#449dab'
# white   = '#787c99'
#
# # Bright colors
# [colors.bright]
# black   = '#444b6a'
# red     = '#ff7a93'
# green   = '#b9f27c'
# yellow  = '#ff9e64'
# blue    = '#7da6ff'
# magenta = '#bb9af7'
# cyan    = '#0db9d7'
# white   = '#acb0d0'

# aurora

[colors.primary]
foreground = '#a9b1d6'
background = '#211c2f'

[colors.selection]
text = "#141425"

[colors.normal]
black = "#5f5f87"
red = "#ff5874"
green = "#addb67"
yellow = "#ecc48d"
blue = "#4c77e4"
magenta = "#be9af7"
cyan = "#A1EFE4"
white = "#e7c3fb"

[colors.bright]
black = "#5f5f87"
red = "#d93234"
green = "#9ec410"
yellow = "#ffbe00"
blue = "#2782d4"
magenta = "#b77ee0"
cyan = "#54ced6"
white = "#ececec"
